from .accountSerializer import AccountSerializer
from .userSerializer import UserSerializer
from .preInscriptionSerializer import PreinscripcionSerializer
from .matchResultSerializer import MatchResultSerializer
from .teamsSerializerRead import teamsSerializerRead
from .teamsSerializerWrite import teamsSerializerWrite