# Generated by Django 4.0.4 on 2022-05-18 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('first_name', models.CharField(max_length=30, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=30, verbose_name='LastName')),
                ('cedula', models.CharField(default='', max_length=30, verbose_name='Cedula')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEquipo', models.CharField(max_length=30, verbose_name='NombreEquipo')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Preinscripcion',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('aceptado', models.BooleanField()),
                ('nombreEquipo', models.CharField(max_length=30, verbose_name='NombreEquipo')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('nombre_encargado', models.CharField(max_length=30, verbose_name='NombreEquipo')),
                ('apellido_encargado', models.CharField(max_length=30, verbose_name='NombreEquipo')),
                ('telefono_encargado', models.CharField(max_length=30, verbose_name='NombreEquipo')),
                ('fecha_preinscripcion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('marcador_local', models.IntegerField(default=0)),
                ('marcado_visita', models.IntegerField(default=0)),
                ('fecha_partido', models.DateTimeField()),
                ('equipo_local', models.ForeignKey(default='Unnasigned', on_delete=django.db.models.deletion.CASCADE, related_name='Equipo1', to='authApp.equipo')),
                ('equipo_visita', models.ForeignKey(default='Unnasigned', on_delete=django.db.models.deletion.CASCADE, related_name='Equipo2', to='authApp.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('equipo', models.ForeignKey(default='Unnasigned', on_delete=django.db.models.deletion.CASCADE, to='authApp.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('lastChangeDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
