# Generated by Django 4.0.4 on 2022-05-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preinscripcion',
            name='fecha_preinscripcion',
            field=models.DateField(),
        ),
    ]
